import nodemailer from 'nodemailer';
import { config } from '../../config';
import { createSupabaseClient } from '../../config/supabase';

interface DigestResult {
  sent: boolean;
  recipientCount?: number;
  contentCount?: number;
  reason?: string;
  message?: string;
}

export class EmailDigestService {
  private transporter: nodemailer.Transporter | null = null;
  private accessToken?: string;

  constructor(accessToken?: string) {
    this.accessToken = accessToken;
    if (config.gmail.user && config.gmail.appPassword) {
      this.transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
          user: config.gmail.user,
          pass: config.gmail.appPassword,
        },
      });
    } else {
      console.warn('⚠️  Gmail credentials not configured - email digest disabled');
    }
  }

  async sendDigest(): Promise<DigestResult> {
    if (!this.transporter) {
      return {
        sent: false,
        reason: 'email_not_configured',
        message: 'Gmail credentials not configured',
      };
    }

    // Get pending content drafts
    const supabase = createSupabaseClient(this.accessToken);
    const { data: contentDrafts, error } = await supabase
      .from('content_drafts')
      .select(
        'id, trend_id, platform, content_type, content, hashtags, status, created_at, trends(id, title, url, scored_trends(relevance_score, keyword_matches))'
      )
      .eq('status', 'pending')
      .order('created_at', { ascending: false })
      .limit(10);

    if (error) {
      throw error;
    }

    if (!contentDrafts || contentDrafts.length === 0) {
      return {
        sent: false,
        reason: 'no_pending_content',
        message: 'No pending content to send in digest',
      };
    }

    // Build email HTML
    const emailHtml = this.buildDigestEmail(contentDrafts);

    // Send email
    const recipients = process.env.DIGEST_RECIPIENTS?.split(',').map(e => e.trim()) || [config.gmail.user!];

    try {
      await this.transporter.sendMail({
        from: config.gmail.user,
        to: recipients.join(', '),
        subject: `Content Intelligence Digest - ${new Date().toLocaleDateString()}`,
        html: emailHtml,
      });

      console.log(`✅ Digest sent to ${recipients.length} recipients`);

      return {
        sent: true,
        recipientCount: recipients.length,
        contentCount: contentDrafts.length,
      };
    } catch (error) {
      console.error('❌ Error sending digest:', error);
      throw error;
    }
  }

  private buildDigestEmail(contentDrafts: any[]): string {
    const contentByPlatform: Record<string, any[]> = {
      twitter: [],
      linkedin: [],
      instagram: [],
    };

    for (const draft of contentDrafts) {
      if (contentByPlatform[draft.platform]) {
        contentByPlatform[draft.platform].push(draft);
      }
    }

    let html = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
    h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
    h2 { color: #34495e; margin-top: 30px; }
    .content-item { background: #f8f9fa; border-left: 4px solid #3498db; padding: 15px; margin: 15px 0; border-radius: 4px; }
    .trend-info { background: #e8f4f8; padding: 10px; margin: 10px 0; border-radius: 4px; font-size: 0.9em; }
    .hashtags { color: #3498db; margin-top: 10px; }
    .score { font-weight: bold; color: #27ae60; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 0.9em; color: #7f8c8d; }
  </style>
</head>
<body>
  <h1>📊 Content Intelligence Digest</h1>
  <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
  <p><strong>Total Content Pieces:</strong> ${contentDrafts.length}</p>
`;

    for (const [platform, drafts] of Object.entries(contentByPlatform)) {
      if (drafts.length === 0) continue;

      html += `<h2>📱 ${platform.charAt(0).toUpperCase() + platform.slice(1)} (${drafts.length})</h2>`;

      for (const draft of drafts) {
        const trend = draft.trend || draft.trends;
        const scored = trend?.scoredTrend || trend?.scored_trends;

        html += `
<div class="content-item">
  <div class="trend-info">
    <strong>Source Trend:</strong> ${trend.title || 'No title'}<br>
    <strong>Relevance Score:</strong> <span class="score">${scored?.relevanceScore ?? scored?.relevance_score ?? 'N/A'}</span><br>
    <strong>Keywords:</strong> ${(scored?.keywordMatches ?? scored?.keyword_matches)?.join(', ') || 'None'}<br>
    <strong>URL:</strong> <a href="${trend.url}">${trend.url}</a>
  </div>
  <p><strong>Content:</strong></p>
  <p>${draft.content}</p>
  <p class="hashtags"><strong>Hashtags:</strong> ${draft.hashtags.join(' ')}</p>
</div>
`;
      }
    }

    html += `
  <div class="footer">
    <p>This digest was automatically generated by the Content Intelligence System.</p>
    <p>Review and approve content at your dashboard.</p>
  </div>
</body>
</html>
`;

    return html;
  }
}
